server:
  port: 3344

spring:
  application:
    name: springcloud-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/bestyuantao/springcloud-config-lean.git

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false